IMAGE:
  WIDTH: 640
  HEIGHT: 480
  Y_OFFSET: 390
  Y_GAP: 25
  Y_GAIN: 1.35

XYCAR:
  START_SPEED: 21.0
  MAX_SPEED: 21.0
  MIN_SPEED: 8.0
  SPEED_CONTROL_THRESHOLD: 35.0
  ACCELERATION_STEP: 0.2
  DECELERATION_STEP: 0.05

PID:
  P_GAIN: 0.47
  I_GAIN: 0.000
  D_GAIN: 0.007

MOVING_AVERAGE_FILTER:
  SAMPLE_SIZE: 30

CANNY:
  LOW_THRESHOLD : 100
  HIGH_THRESHOLD : 150

HOUGH:
  MIN_PIXEL : 40
  MIN_LINE : 35
  MAX_GAP : 10

TOPIC:
  PUB_NAME: /xycar_motor
  SUB_NAME: /usb_cam/image_raw/
  QUEUE_SIZE: 1

DEBUG: False
